# Configuration for GitHub's Dependabot
# @see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 5
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    cooldown:
      default-days: 5
    directory: /
    schedule:
      interval: daily
    groups:
      minor-versions:
        update-types:
          - minor
          - patch
