version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn build:dev
      - yarn build:prod
  post_build:
    commands:
      - aws s3 cp --recursive dist s3://touch-pricker.simpleigh.com/
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION} --paths '/*'
