# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax

name: Build

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v6

      - name: Setup Node
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn prettier --check .

      - name: Test
        run: yarn jest --ci --coverage

      - name: Publish test coverage
        # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build docs
        run: yarn typedoc

  website:
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-website.yml
    secrets: inherit
